### ISSUE TITLE
Failed to connect to ESP32: Timed out waiting for packet header

### ISSUE THREAD

**Issue by Yacal999** [joelsernamoreno/EvilCrow-RF#17]
Hello, after solving the problem mentioned in the last issue (the COM port one), Ive encountered another problem. Now, when I try to flash my unit in Arduino, it compiles god, but when it is time to upload the code, it keeps connecting for a while, and then it just drops an error:

Arduino:1.8.13 (Windows 10), Tarjeta:"ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), DIO, 80MHz, 4MB (32Mb), 921600, Core 1, Core 1, None"

El Sketch usa 802349 bytes (61%) del espacio de almacenamiento de programa. El máximo es 1310720 bytes.

Las variables Globales usan 34460 bytes (10%) de la memoria dinámica, dejando 293220 bytes para las variables locales. El máximo es 327680 bytes.

esptool.py v3.1

Serial port COM6

Connecting........_____....._____....._____....._____....._____....._____....._____

A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header

A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header

Ive tried reintalling esptool and pyserial, reinstalling the drivers, try to flash it in other computers, with Windows and Linux, but same error keeps appearing. Im totally frustrated with this, first my PC couldnt recognise the devicve in the COM port, and now this. I know it not your fault, but looks like I had bad luck with this device. All help will be appreciated.

**Comment by 0x5c4r3** [comment]
Unfortunately I get the same error, trying to upload a simple sketch and I get this.. Arduino detects the port no problems, it just output this error.
**OS:** macOS Monterey v12.2
**Drivers:** CP210xVCP Driver v6.0.2
![image](https://user-images.githubusercontent.com/16732213/153179910-f9f09927-e899-41a4-ae69-c22d3c5be1b3.png)

**Comment by joelsernamoreno** [comment]
Hello!

I don't have any Mac computer to support here, can you try this on windows?

**Comment by 0x5c4r3** [comment]
Yes I will give it a check on windows and let you know. In the meanwhile, Kali (debian based) does not detect the ECRF nor it load the /dev/ttyUSB0.

**Comment by joelsernamoreno** [comment]
Well, try to load this in windows (try not to use virtual machine). If you don't get this, write me privately on twitter (@JoelSernaMoreno) or telegram (@JoelSerna) and I can connect remotely to look at this
