### ISSUE TITLE
bad USB ?

### ISSUE THREAD

**Issue by oshri-almog** [joelsernamoreno/EvilCrow-RF#20]
![image](https://user-images.githubusercontent.com/10677764/149658790-f1328f79-2aef-4751-bf65-2290c6d50796.png)

Are you familiar with this issue?
What are my options To debug this issue and solve it myself?
Most likely I need to solder one of the wires to the usb?
p.s.
I can login to the web UI.

**Comment by tompusey** [comment]
I had the same problem initially, have a look at issue 16 for the fix. [https://github.com/joelsernamoreno/EvilCrow-RF/issues/16]

**Comment by joelsernamoreno** [comment]
Exactly, check what @tompusey says

**Comment by oshri-almog** [comment]
Thanks a lot it's work
