### ISSUE TITLE
Can’t find device on arduino IDE

### ISSUE THREAD

**Issue by merdeux50** [joelsernamoreno/EvilCrow-RF#22]
Hello,

I’ve finally got the evil crow rf from Aliexp, but I can’t connect to it via arduino ide, I use OS X. I’ve tried via virtualbox running Windows 7 and 10, and no luck. 

Even using it as is, I manage to connect to the device with my phone but it doesn’t seem to log any data.

Please help.

**Comment by joelsernamoreno** [comment]
Hi!

I don't have a Mac and virtual machines don't work well here

How are you configuring Evil Crow RF and what remote control are you using?

Join the discord channel, there you can ask questions and we will try to fix the problem
