### ISSUE TITLE
RollJam attack

### ISSUE THREAD

**Issue by sumanblack666** [joelsernamoreno/EvilCrow-RF#5]
Hi ..bought this at aliexpress and still waiting to receive it ...cant wait to play with it ...wondering why there's no samy's rolljam attack module available , i saw its available at https://github.com/rfquack/RFQuack/tree/8a9364766192ae660c95ee0392152190ab1d1176/src/modules/defaults ?

is this due to security reasons ?

**Comment by joelsernamoreno** [comment]
Hi!

Are you talking about adding rolljam in the basic firmware?

**Comment by sumanblack666** [comment]
Yes ..

**Comment by joelsernamoreno** [comment]
I don't have that much free time to implement features that fast. We are currently working on a library for Evil Crow RF that does not depend on rc-switch. We're also working on properly adapting the latest version of SmartRC here. With the latest version of SmartRC there are some problems to use both radio modules at the same time, so the library in this repository is version 2.3.

The community can add new features to Evil Crow RF, you can PR if you have something new for the device :)

**Comment by sumanblack666** [comment]
Understood .I'll try to implement once i receive the device .

**Comment by joelsernamoreno** [comment]
Thank you!

I hope you understand this. The devices are developed in our free time and we don't make money with this, so we try to make them as cheap as possible

We can't offer a great feature support like hak5 or Great Scott Gadgets

**Comment by LeonSmall512** [comment]
How much will u charge me to make a rolljam device.
