### ISSUE TITLE
Don't see any logs in web view

### ISSUE THREAD

**Issue by davidchatting** [joelsernamoreno/EvilCrow-RF#7]
Hi - I received my board today - thanks!

I uploaded the lastest code (the EvilCrow-RF.ino sketch) via Arduino, but I don't see any logs in web view after I have set the rx parameters - I have tried periodically refreshing but that doesn't work - and I also don't see anything in the Serial terminal. If I use ASK_RAW_RX.ino instead I do get sensible looking ressults - so something's working - any clues?

Cheers,
David

**Comment by davidchatting** [comment]
Thanks for the speedy reply - I will look at the SmartRC library as you suggest

**Comment by davidchatting** [comment]
It works! :) Taking that example (ProtocolAnalyzeDemo_cc1101.ino) and making sure I had your version of the ELECHOUSE_CC1101_SRC_DRV library and the protocollessreceiver branch of rc-switch - I addded in your CC1101 pins definitions, made a call to ELECHOUSE_cc1101.setSpiPin(sck, miso, mosi, csn1) and removed the ELECHOUSE_cc1101.getCC1101() check because it was failing.

THANKS!

**Comment by joelsernamoreno** [comment]
Hello!

Try the new sketch EvilCrowRF-RAW.ino. This is a combination of Raw Rx and Raw Tx.

In the readme.md it has a section where it explains how to set this up from the web panel

You can perform replay attacks with this :)
