### ISSUE TITLE
next production batch ?

### ISSUE THREAD

**Issue by timFaivre** [joelsernamoreno/EvilCrow-RF#8]
Hi,
sorry in advance to reach you here, but, ... 

I see the hardware as unvailable on aliexpress : do you plan to lauch a second batch anytime soon ? I would be interested. Perhaps using croud supply if you need financing ?

**Comment by joelsernamoreno** [comment]
Hello!

A few days ago we made the second batch with 29 devices. This sold out very fast

The manufacturer is making 100 devices to sell. I hope it doesn't take them too long to make this available for sale

I will write you here when Evil Crow RF is available :)

**Comment by timFaivre** [comment]
Awesome ! I'm staying tuned.

**Comment by MrTakfly** [comment]
It works every time in Windows 👍 Thank you for your help!

I'm currently implementing a multi-bank memory for recording and replaying signals. It's a bit clunky at the minute, but once I've polished it I will add a web interface and submit a PR! Again, great project! You're a wizard!

**Comment by Pr0l1f1c** [comment]
Great tool, I'm excited myself to buy a few for my team! Thanks!

**Comment by joelsernamoreno** [comment]
Hi
I think the stock will return this week

**Comment by opless** [comment]
Hi, sorry for the comment spam, I'm also interested so commenting to receive updates.

**Comment by gigawatts** [comment]
28 in stock right now

**Comment by joelsernamoreno** [comment]
Stock!

**Comment by Pr0l1f1c** [comment]
Thx for the heads up! I need a total of 28 for a class room but settled for 4 this time to allow others a chance to grab one. Thx again!

**Comment by joelsernamoreno** [comment]
Hi @Pr0l1f1c 

Hello

You can write me on twitter (@JoelSernaMoreno) and I will put you in contact with the manufacturer if you need a batch of several devices

Thanks!

**Comment by joelsernamoreno** [comment]
I close this issue. If you ever need to know when new stock is available, please open a new issue

Thanks
